name: 도이치모터스 뉴스봇

# 매일 한국시간 오후 4시 00분에 자동 실행
on:
  schedule:
    - cron: '00 7 * * *'  # UTC 07:00 = 한국시간 16:00
  
  # 수동 실행도 가능 (테스트용)
  workflow_dispatch:

jobs:
  send-news:
    runs-on: ubuntu-latest
    
    steps:
    # 1. 코드 가져오기
    - name: 코드 다운로드
      uses: actions/checkout@v4
    
    # 2. Python 설치
    - name: Python 설치
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    # 3. 필요한 라이브러리 설치
    - name: 라이브러리 설치
      run: |
        pip install requests
    
    # 4. 뉴스봇 실행
    - name: 뉴스 전송
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      run: |
        python telegram_news_bot.py
