name: 도이치모터스 뉴스봇

on:
  schedule:
    - cron: '0 0 * * *'  # 한국시간 8:00
  workflow_dispatch:

permissions:
  contents: write

jobs:
  send-news:
    runs-on: ubuntu-latest

    env:
      GITHUB_REPO: frozen-seaweed/deutschmotors-news-bot
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install requests; fi


      - name: Run news bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: python telegram_news_bot.py
